name: Feature request
description: Suggest an idea for this project
title: "[Feature Request] "
labels:
  - enhancement
assignees: unknowIfGuestInDream
body:
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the feature is, and what it wiill enhance or solve. Ex. I'm always frustrated when [...]

  - type: textarea
    id: solution-context
    attributes:
      label: Describe the solution you'd lik
      placeholder: A clear and concise description of what you want to happen.

  - type: textarea
    id: considered-context
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
