name: Artifact

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.9'
    - name: Build with Maven
      run: mvn -B clean verify -ntp
    - name: Archive plugin dist
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: sites/com.tlcsdm.eclipse.translation.site/target/*.zip
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: update_site
        path: sites/com.tlcsdm.eclipse.translation.site/target/repository
